services:
  api:
    build:
      context: .
      args:
        INSTALL_DEV: "true"
    command:
      ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/app:rw
      - ./tests:/app/tests:ro
      - ./pytest.ini:/app/pytest.ini:ro
